### ISSUE TITLE
Occasional core dump under high load

### ISSUE THREAD

**Issue by rtitle** [zmartzone/mod_oauth2#27]
Hello,

Thank you for this project. I am trying to migrate from `mod_auth_openidc` and things are generally working well. However I occasionally get a `double free` error + core dump, usually under high load. From `error.log`:

```
double free or corruption (out)
[Wed Mar 02 17:02:55.578479 2022] [core:notice] [pid 50:tid 139818184620992] AH00051: child pid 2220 exit signal Aborted (6), possible coredump in /cores
```

I was able to get a stack trace from the core dump:
```
Thread 121 (Thread 0x7f29e52e0700 (LWP 799)):
#0  0x00007f29f44e3177 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  <signal handler called>
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#3  0x00007f29f44e47f1 in __GI_abort () at abort.c:79
#4  0x00007f29f452d837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f29f465aa7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#5  0x00007f29f45348ba in malloc_printerr (str=str@entry=0x7f29f465c788 "double free or corruption (out)") at malloc.c:5342
#6  0x00007f29f453be4a in _int_free (have_lock=0, p=0x7f29d8003200, av=0x7f29f488fc40 <main_arena>) at malloc.c:4308
#7  __GI___libc_free (mem=0x7f29d8003210) at malloc.c:3134
#8  0x00007f29f3163cd9 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#9  0x00007f29f317065d in curl_easy_cleanup () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#10 0x00007f29ea9b5810 in ?? () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#11 0x00007f29ea9b596e in oauth2_url_encode () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#12 0x00007f29ea9c7211 in ?? () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#13 0x00007f29ea9c7305 in ?? () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#14 0x00007f29ea9b6fd7 in oauth2_nv_list_loop () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#15 0x00007f29ea9c7541 in oauth2_http_url_form_encode () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#16 0x00007f29ea9c83a7 in oauth2_http_post_form () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#17 0x00007f29ea9cb4ad in ?? () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#18 0x00007f29ea9cb743 in ?? () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#19 0x00007f29ea9cc6ef in oauth2_token_verify () from /usr/lib/x86_64-linux-gnu/liboauth2.so.0
#20 0x00007f29eabe9a0b in ?? () from /usr/lib/apache2/modules/mod_oauth2.so
#21 0x00007f29eabe9f25 in ?? () from /usr/lib/apache2/modules/mod_oauth2.so
#22 0x000055821c4a5480 in ap_run_check_user_id ()
#23 0x000055821c4a8063 in ap_process_request_internal ()
#24 0x000055821c4c7228 in ap_process_async_request ()
#25 0x000055821c4c38e0 in ?? ()
#26 0x000055821c4b9090 in ap_run_process_connection ()
#27 0x00007f29eb001ecf in ?? () from /usr/lib/apache2/modules/mod_mpm_event.so
#28 0x00007f29eb0028e5 in ?? () from /usr/lib/apache2/modules/mod_mpm_event.so
#29 0x00007f29f489c6db in start_thread (arg=0x7f29e52e0700) at pthread_create.c:463
#30 0x00007f29f45c561f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I think that is somewhere around this code: https://github.com/zmartzone/liboauth2/blob/fdc6b2f0fc1255925359cae3e83471a20347d687/src/util.c#L293

Regarding my setup, I am using token introspection: 
```
OAuth2TokenVerify introspect https://... introspect.ssl_verify=false&verify.iat=skip
```

I am also using `mpm_event` with fairly high concurrency:
```
<IfModule mpm_event_module>
StartServers			 25
ServerLimit             100
MinSpareThreads		 5
MaxSpareThreads		 3000
ThreadsPerChild		 120
ThreadLimit			 256
MaxRequestWorkers	  12000
MaxConnectionsPerChild   10000
</IfModule>
```

Apache version:
```
# apache2 -V 
[Thu Mar 03 01:42:20.288165 2022] [core:warn] [pid 51911] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2022-01-05T14:50:41
Server's Module Magic Number: 20120211:68
Server loaded:  APR 1.6.3, APR-UTIL 1.6.1
Compiled using: APR 1.6.3, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"
```

Any insights would be greatly appreciated, I'm fairly stuck. Thank you.

**Comment by zandbelt** [comment]
thanks for the report and stacktrace; that should be fixed in the new release of liboauth2 version 1.4.4.1:
https://github.com/zmartzone/liboauth2/releases/tag/v1.4.4.1
