### ISSUE TITLE
Segmentation fault (core dumped) on Debian 10

### ISSUE THREAD

**Issue by WMP** [zmartzone/mod_oauth2#7]
I compile mod_oauth2 and liboauth2 on debian10, and i have `Segmentation fault (core dumped)` after few minutes (one time after 30 seconds, other time after 5 minutes....). 

Full log:
```
[Tue Sep 01 12:52:33.983683 2020] [mpm_event:notice] [pid 2392:tid 140672166208640] AH00492: caught SIGWINCH, shutting down gracefully
Segmentation fault (core dumped)
Action '-D FOREGROUND' failed.
The Apache error log may have more information
```
In core dump i have:
```
(gdb) bt full
#0  0x00007ff0ca4c973f in oauth2_apache_child_cleanup (data=0x555d629dceb0, m=0x7ff0ca503180 <oauth2_module>, 
    package_name_version=0x7ff0ca501013 "mod_oauth2-3.1.0") at src/server/apache.c:144
        cfg = 0x0
        sp = 0x555d629dceb0
#1  0x00007ff0ca4c9812 in oauth2_apache_parent_cleanup (data=0x7ff0ca7c44a0, m=0x7ff0ca503180 <oauth2_module>, 
    package_name_version=0x7ff0ca501013 "mod_oauth2-3.1.0") at src/server/apache.c:161
        s = 0x7ff0ca7c44a0
        cfg = 0x555d629dceb0
        __FUNCTION__ = "oauth2_apache_parent_cleanup"
#2  0x00007ff0caa85a3e in apr_pool_destroy () from /usr/lib/x86_64-linux-gnu/libapr-1.so.0
No symbol table info available.
#3  0x00007ff0caa85a15 in apr_pool_destroy () from /usr/lib/x86_64-linux-gnu/libapr-1.so.0
No symbol table info available.
#4  0x0000555d6156e4e8 in ?? ()
No symbol table info available.
#5  0x0000555d6156dfa1 in main ()
No symbol table info available.
(gdb)
```

Apache2 version:
```
apache2 -V 
[Tue Sep 01 13:25:59.937675 2020] [core:warn] [pid 2637] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot
Server version: Apache/2.4.38 (Debian)
Server built:   2019-10-15T19:53:42
Server's Module Magic Number: 20120211:84
Server loaded:  APR 1.6.5, APR-UTIL 1.6.1
Compiled using: APR 1.6.5, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"
```

**Comment by zandbelt** [comment]
it looks like you're running Apache in the foreground in a terminal window that you're resizing:
https://stackoverflow.com/questions/780853/what-is-in-apache-2-a-caught-sigwinch-error

It does seem there's a problem with resource cleanups on graceful restarts, but for now I would avoid those (by running in the background and using full stop/start, or just not resizing the window when testing)

I'll keep this open to investigate graceful restarts.

**Comment by brownp2k** [comment]
For what it's worth, this is still happening for restarts in 3.2.0 on Centos7.

**Comment by zandbelt** [comment]
ack, I did not work on this yet (full restart is your rescue)

**Comment by zandbelt** [comment]
can you try https://github.com/zmartzone/liboauth2/commit/7de0b49d5a50dd4ce682a4d9a58cb2ffafbdb38f ?

**Comment by brownp2k** [comment]
3 days in with using 7de0b49 and no apparent issues so far.
